name: Hello World
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2 
        - name: create prog
          run: echo "Running makefile"
        - run: g++ ./Exer3/hello.cpp && ./a.out
