name: Hello World
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: echo "Running makefile" 
        - name: create prog
          run: g++ ../../Exer3/hello.cpp
        - run: ./a.out
